### ISSUE TITLE
'spout t' output becomes unreadable with minitest 5.11 and above

### ISSUE THREAD

**Issue by mrueschman** [sleepepi/spout#102]
This may resolve itself over time, but updates to minitest appear to have impacted the 'spout t' output, making it more difficult to read/process.

In the interim, we will add the following to the data dictionary Gemfile.

```
gem 'minitest', '~> 5.10.3'
```

minitest 5.10.3

![image](https://user-images.githubusercontent.com/707167/36544198-dffeecd4-17b3-11e8-8f71-d591a5cfc1a9.png)

minitest 5.11.3 (DictionaryTest shows up repeatedly and fills terminal window buffer)

![image](https://user-images.githubusercontent.com/707167/36544160-c9db4cd6-17b3-11e8-8837-6ae00008c58a.png)

**Comment by remomueller** [comment]
@mrueschman can you try out v0.13.0.beta2 to see if this still causes an issue? Also, what version of ruby were you using?

**Comment by mrueschman** [comment]
Seems cleared up in beta2 and now using ruby 2.5.1. Thanks!

**Comment by remomueller** [comment]
Great, thanks! Closing this issue.
