### ISSUE TITLE
Upon deploying, "Sueño" being re-written as "Sue├▒o"

### ISSUE THREAD

**Issue by mrueschman** [sleepepi/spout#104]
![image](https://user-images.githubusercontent.com/707167/50781166-ad070180-1272-11e9-8858-ced6e6d481f5.png)

Happening as part of HCHS 0-4-stable work I am doing. Last dataset  push was on spout 0.11.1, but now using 0.14.1.

**Comment by remomueller** [comment]
Looks like it may have something to do with this line: https://github.com/sleepepi/spout/blob/master/lib/spout/helpers/json_request.rb#L88

```
CGI.escape(value.to_s)
```
