### ISSUE TITLE
Make graphs for integer variables only group into integer categories

### ISSUE THREAD

**Issue by mrueschman** [sleepepi/spout#72]
For instance: https://www.sleepdata.org/datasets/cfs/variables/alcohday (even though this is numeric now, an integer variable would do the same)

Ideally bars would be shown for 0 days, 1 day, 2 days, etc.

**Comment by remomueller** [comment]
Another example:

https://sleepdata.org/datasets/chat/variables/pedsql_emotional_nmiss_chld
