### ISSUE TITLE
Have dataset values shown somewhere on variable page

### ISSUE THREAD

**Issue by mrueschman** [sleepepi/spout#78]
If I am looking at a variable page and working with the dataset simultaneously, I may want to have a quick/simple way to reference dataset values without digging into the data dictionary domain file.

For instance: https://www.sleepdata.org/datasets/shhs/variables/sh319b

Are the values 0 to 3? 1 to 4? It would be useful to have the ability to find this information on the variable page.

![image](https://cloud.githubusercontent.com/assets/707167/10941218/6890ad44-82d8-11e5-9158-a42a90c1fd0d.png)

**Comment by remomueller** [comment]
This issue may be able to be fixed in nsrr/www.sleepdata.org repository itself.

**Comment by remomueller** [comment]
This is part of [NSRR milestone 0.18.0](https://github.com/nsrr/www.sleepdata.org/milestones/0.18.0)
