### ISSUE TITLE
Have charts and data tables go to same number of decimal places

### ISSUE THREAD

**Issue by mrueschman** [sleepepi/spout#79]
https://www.sleepdata.org/datasets/shhs/variables/mi

Ying brought this up in regards to the variable below, where the mean values in the data table are rounded to "0.0" from "0.02" and "0.01" from the chart above.

Is the number of places after the decimal automatically set somewhere? In this instance, I'd like the data table values to go to two decimal places to match the chart above.

![image](https://cloud.githubusercontent.com/assets/707167/10969485/a50c2c62-8396-11e5-8b78-382601718e3d.png)

**Comment by remomueller** [comment]
Interesting, I think spout may need to be smarter in setting precision for the mean in this case. Will try for an automatic approach first, but we may have to change it so we add `precision` or `significant digits` or something like that to the specific variables if not.

**Comment by mrueschman** [comment]
I wondered if it could be done "smartly".
