### ISSUE TITLE
Allow numeric/integer variables to have domains

### ISSUE THREAD

**Issue by mrueschman** [sleepepi/spout#92]
See this issue for reference: https://github.com/sleepepi/sof-data-dictionary/issues/35

This numeric age should allow values like "G" and "H", since these missing codes have actual meaning and shouldn't simply be set to null.

This will have graph considerations since currently these oddball values are graphed as 0, while they should probably be ignored for graphing purposes.

**Comment by remomueller** [comment]
Moving to 0.11.2
